version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app/client
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    command: npm start
