name: Full-Stack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Frontend (React)
      - name: Install dependencies (frontend)
        run: |
          cd client
          npm install

      - name: Build frontend (React)
        run: |
          cd client
          npm run build

      # Step 4: Backend (Node.js)
      - name: Install dependencies (backend)
        run: |
          cd server
          npm install

      - name: Run backend (Node.js)
        run: |
          cd server
          npm run dev &
        env:
          PORT: ${{ secrets.PORT }}
          DATABASE: ${{ secrets.DATABASE }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
          JWT_COOKIE_EXPIRE: ${{ secrets.JWT_COOKIE_EXPIRE }}

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy React to Netlify
      - name: Deploy React App to Netlify
        run: echo "Deployed on Netlify" # Replace with actual deploy command if needed.

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Deploy Node.js to Render
      - name: Deploy Backend to Render
        run: echo "Deployed on Render" # Replace with actual deploy command if needed.
